version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-9.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: khoa123456
      MYSQL_DATABASE: jiramicroservice
    volumes:
      - mysql-data:/var/lib/mysql
    platform: linux/x86_64
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    image: openjdk:17
    container_name: jiramicroservice
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/jiramicroservice
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: khoa123456
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: ./gradlew bootRun

volumes:
  mysql-data: